// Package repo — qa_test_suites adapter (QA continuous test loop).
//
// QATestSuitesRepo dual-pools like ApprovalRepo: the admin pool services the
// activity-side Upsert (the Temporal worker has no request tx / GUC bound)
// AND the cron-side list/record calls (the QA loop goroutine runs with
// context.Background and no principal, so it MUST bypass RLS to sweep every
// org). The app pool is kept for future RLS-scoped HTTP reads of the suite
// list; nothing mounts one today.
package repo

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/nexis-eco/nexis/services/control-plane/internal/domain"
)

// QATestSuitesRepo persists qa_test_suites rows.
type QATestSuitesRepo struct {
	pool      *pgxpool.Pool
	adminPool *pgxpool.Pool
}

// NewQATestSuitesRepo constructs the repo. adminPool may be nil — falls back
// to pool so single-pool tests still work.
func NewQATestSuitesRepo(pool, admin *pgxpool.Pool) *QATestSuitesRepo {
	if admin == nil {
		admin = pool
	}
	return &QATestSuitesRepo{pool: pool, adminPool: admin}
}

// SaveSuite upserts the suite generated by a recovery run. Keyed on
// workflow_run_id so an activity retry overwrites rather than duplicates.
// A re-generation resets last_status to 'unknown' — the new tests have no
// pass/fail history yet. Admin pool: the caller is the QATestGen activity.
func (r *QATestSuitesRepo) SaveSuite(ctx context.Context, s domain.QATestSuite) error {
	testsJSON, err := json.Marshal(s.Tests)
	if err != nil {
		return fmt.Errorf("qa_test_suites: marshal tests: %w", err)
	}
	covers := s.CoversFiles
	if covers == nil {
		covers = []string{}
	}
	coversJSON, err := json.Marshal(covers)
	if err != nil {
		return fmt.Errorf("qa_test_suites: marshal covers_files: %w", err)
	}
	var wsID, projID any
	if s.WorkspaceID != "" {
		wsID = s.WorkspaceID
	}
	if s.ProjectID != "" {
		projID = s.ProjectID
	}
	_, err = r.adminPool.Exec(ctx, `
        INSERT INTO qa_test_suites
          (org_id, workspace_id, project_id, workflow_run_id, repo_sha, tests, covers_files)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        ON CONFLICT (workflow_run_id) DO UPDATE SET
          repo_sha     = EXCLUDED.repo_sha,
          tests        = EXCLUDED.tests,
          covers_files = EXCLUDED.covers_files,
          last_status  = 'unknown',
          updated_at   = now()`,
		s.OrgID, wsID, projID, s.WorkflowRunID, s.RepoSHA, testsJSON, coversJSON,
	)
	if err != nil {
		return fmt.Errorf("qa_test_suites: upsert: %w", err)
	}
	return nil
}

// AdminListActive returns active suites oldest-run-first (never-run rows
// first) so every suite eventually gets a turn under the per-tick cap.
// Cross-org by design — the cron is system-level.
func (r *QATestSuitesRepo) AdminListActive(ctx context.Context, limit int) ([]domain.QATestSuite, error) {
	if limit <= 0 {
		limit = 20
	}
	rows, err := r.adminPool.Query(ctx, `
        SELECT id::text, org_id::text,
               COALESCE(workspace_id::text, ''), COALESCE(project_id::text, ''),
               workflow_run_id::text, repo_sha, tests, covers_files,
               status, last_status, last_fail_count,
               COALESCE(last_run_at, '1970-01-01'::timestamptz), created_at, updated_at
        FROM qa_test_suites
        WHERE status = 'active'
        ORDER BY last_run_at ASC NULLS FIRST
        LIMIT $1`, limit,
	)
	if err != nil {
		return nil, fmt.Errorf("qa_test_suites: list active: %w", err)
	}
	defer rows.Close()
	out := []domain.QATestSuite{}
	for rows.Next() {
		var s domain.QATestSuite
		var testsJSON, coversJSON []byte
		if err := rows.Scan(
			&s.ID, &s.OrgID, &s.WorkspaceID, &s.ProjectID,
			&s.WorkflowRunID, &s.RepoSHA, &testsJSON, &coversJSON,
			&s.Status, &s.LastStatus, &s.LastFailCount,
			&s.LastRunAt, &s.CreatedAt, &s.UpdatedAt,
		); err != nil {
			return nil, err
		}
		if err := json.Unmarshal(testsJSON, &s.Tests); err != nil {
			return nil, fmt.Errorf("qa_test_suites: decode tests for %s: %w", s.ID, err)
		}
		if len(coversJSON) > 0 {
			_ = json.Unmarshal(coversJSON, &s.CoversFiles)
		}
		out = append(out, s)
	}
	return out, rows.Err()
}

// AdminRecordRun stamps the outcome of one loop pass over a suite.
func (r *QATestSuitesRepo) AdminRecordRun(ctx context.Context, suiteID string, passed bool, failCount int, at time.Time) error {
	status := domain.QASuiteRunFailed
	if passed {
		status = domain.QASuiteRunPassed
	}
	_, err := r.adminPool.Exec(ctx, `
        UPDATE qa_test_suites
        SET last_status = $1, last_fail_count = $2, last_run_at = $3, updated_at = now()
        WHERE id = $4`,
		status, failCount, at.UTC().Truncate(time.Microsecond), suiteID,
	)
	if err != nil {
		return fmt.Errorf("qa_test_suites: record run: %w", err)
	}
	return nil
}
