// Package slack — interactivity request parsing + signature verification.
//
// Slack interactivity (button clicks, shortcut triggers, modal submits) all
// land on a single HTTPS endpoint configured in the App's "Interactivity &
// Shortcuts" panel. The wire shape is application/x-www-form-urlencoded with
// one field named "payload" holding a JSON string. Slack signs the *raw*
// request body (not the parsed payload), so the HTTP handler MUST read the
// body once, verify the signature against that exact byte sequence, and only
// then parse the form.
//
// This file owns two responsibilities:
//
//   - VerifyRequestSignature implements https://api.slack.com/authentication/verifying-requests-from-slack
//     using the SLACK_SIGNING_SECRET. The signature is
//     "v0=" + hex(hmac-sha256(secret, "v0:" + timestamp + ":" + body)).
//     We reject timestamps older than 5 minutes (Slack's documented replay
//     window) and use crypto/subtle.ConstantTimeCompare for the equality
//     check so a timing oracle can't be built against us.
//
//   - ParseInteractivity turns the form-encoded "payload" field into a typed
//     InteractivityPayload the handler can dispatch on. We only model the
//     "block_actions" shape — shortcuts and modals are out of phase for the
//     Approval Gate but the type's Type field surfaces enough to reject
//     unsupported shapes cleanly.
package slack

import (
	"crypto/hmac"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"strconv"
	"time"
)

// signatureWindow is the Slack-documented replay window. Requests older than
// this are rejected even when the HMAC is otherwise valid — the timestamp is
// part of the signed string, but a stolen request from 6 minutes ago would
// still verify HMAC-only without this check.
const signatureWindow = 5 * time.Minute

// nowFunc is the package-level clock injection seam. Tests overwrite this via
// SetNowForTest; production callers leave it as time.Now. Keeping it
// package-level (rather than a parameter) lets the handler skip wiring a
// clock through every call site.
var nowFunc = time.Now

// SetNowForTest replaces the package clock; tests call this in a t.Cleanup
// stanza to restore time.Now afterwards. NOT safe for production use.
func SetNowForTest(f func() time.Time) (restore func()) {
	prev := nowFunc
	nowFunc = f
	return func() { nowFunc = prev }
}

// ErrInvalidSignature is the canonical error returned for every flavour of
// signature-verification failure: missing header, malformed header, stale
// timestamp, HMAC mismatch. The handler maps this to 401 so a single sentinel
// covers every untrusted request.
var ErrInvalidSignature = errors.New("slack: invalid request signature")

// VerifyRequestSignature returns nil when the (timestamp, signature) pair on
// the incoming request was generated by the holder of signingSecret over the
// supplied raw body. Returns ErrInvalidSignature on any mismatch.
//
// signingSecret is the workspace-app's Signing Secret from the Slack app
// console (not the OAuth client secret — those are two distinct values).
//
// timestamp is the X-Slack-Request-Timestamp header value; signature is the
// X-Slack-Signature header value (always prefixed with "v0=").
//
// body is the raw bytes of the request body — the HTTP handler MUST read the
// body before calling this and then re-bind the parsed form for downstream
// use. Slack signs bytes, not a parsed form.
func VerifyRequestSignature(signingSecret, body, timestamp, signature string) error {
	if signingSecret == "" {
		return errors.New("slack: signing secret not configured")
	}
	if timestamp == "" || signature == "" {
		return ErrInvalidSignature
	}
	// Reject stale requests. The timestamp is Unix epoch seconds; parse it
	// and bail if it's older than signatureWindow. Future-dated timestamps
	// also fail — a clock skew on Slack's side would surface as a synced-up
	// SLO breach long before they sign in our future.
	tsNum, err := strconv.ParseInt(timestamp, 10, 64)
	if err != nil {
		return ErrInvalidSignature
	}
	ts := time.Unix(tsNum, 0)
	now := nowFunc()
	if ts.Before(now.Add(-signatureWindow)) || ts.After(now.Add(signatureWindow)) {
		return ErrInvalidSignature
	}

	// Slack's signed string is the literal "v0:<ts>:<raw-body>". Build it
	// once, HMAC it, hex-encode, prefix "v0=".
	mac := hmac.New(sha256.New, []byte(signingSecret))
	fmt.Fprintf(mac, "v0:%s:%s", timestamp, body)
	want := "v0=" + hex.EncodeToString(mac.Sum(nil))

	if subtle.ConstantTimeCompare([]byte(want), []byte(signature)) != 1 {
		return ErrInvalidSignature
	}
	return nil
}

// InteractivityPayload is the typed view of Slack's block_actions payload.
// Only the fields the Approval Gate needs are surfaced — the raw payload is
// much richer (we ignore container.* / message.* / view.* etc).
type InteractivityPayload struct {
	Type    string
	User    InteractivityUser
	Team    InteractivityTeam
	Actions []InteractivityAction
	// ResponseURL is the ephemeral channel Slack hands the handler for
	// follow-up messages — typically used to confirm the decision back to
	// the clicker without an extra chat.postMessage call.
	ResponseURL string
	// TriggerID is required for opening modals; surfaced so future phases can
	// branch (e.g. "Reject" opens a reason modal). Out of phase for v1.
	TriggerID string
}

// InteractivityUser is the slim view of payload.user.
type InteractivityUser struct {
	ID       string
	Username string
	Email    string // populated by Slack when the app has users:read.email
}

// InteractivityTeam is the slim view of payload.team.
type InteractivityTeam struct {
	ID string
}

// InteractivityAction is one entry in payload.actions[]. block_actions
// payloads always carry an array even when only one button was clicked.
type InteractivityAction struct {
	ActionID string
	Value    string // we encode "<approval_id>:<decision>" — see slack_interactivity handler
}

// ParseInteractivity decodes the form-encoded body Slack POSTs. body is the
// already-url.ParseQuery'd values; the caller is responsible for the
// signature check + form parse before invoking this.
//
// Returns a descriptive error when:
//   - the "payload" field is missing entirely
//   - the JSON inside "payload" is malformed
//   - the payload's "type" field is unsupported (we only handle block_actions)
func ParseInteractivity(body url.Values) (InteractivityPayload, error) {
	raw := body.Get("payload")
	if raw == "" {
		return InteractivityPayload{}, errors.New("slack: missing payload field")
	}
	var p struct {
		Type string `json:"type"`
		User struct {
			ID       string `json:"id"`
			Username string `json:"username"`
			Email    string `json:"email"`
		} `json:"user"`
		Team struct {
			ID string `json:"id"`
		} `json:"team"`
		Actions []struct {
			ActionID string `json:"action_id"`
			Value    string `json:"value"`
		} `json:"actions"`
		ResponseURL string `json:"response_url"`
		TriggerID   string `json:"trigger_id"`
	}
	if err := json.Unmarshal([]byte(raw), &p); err != nil {
		return InteractivityPayload{}, fmt.Errorf("slack: decode payload: %w", err)
	}
	if p.Type != "block_actions" {
		return InteractivityPayload{}, fmt.Errorf("slack: unsupported interactivity type %q", p.Type)
	}
	out := InteractivityPayload{
		Type:        p.Type,
		ResponseURL: p.ResponseURL,
		TriggerID:   p.TriggerID,
		User: InteractivityUser{
			ID:       p.User.ID,
			Username: p.User.Username,
			Email:    p.User.Email,
		},
		Team:    InteractivityTeam{ID: p.Team.ID},
		Actions: make([]InteractivityAction, 0, len(p.Actions)),
	}
	for _, a := range p.Actions {
		out.Actions = append(out.Actions, InteractivityAction{
			ActionID: a.ActionID,
			Value:    a.Value,
		})
	}
	return out, nil
}
